apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: "rangotest-c3f4"
    labels:
        app: "rangotest-c3f4"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: default-rangotest-c3f4.14efaeab5490490da430.eastasia.aksapp.io
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                    name: "rangotest-c3f4"
                    port: 
                        number: 80
