apiVersion: v1
kind: Service
metadata:
    name: "rangotest-c3f4"
    labels:
        app: "rangotest-c3f4"
spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "rangotest-c3f4"
